--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-26 01:05:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 868 (class 1247 OID 32822)
-- Name: gender_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.gender_type AS ENUM (
    'male',
    'female',
    'non_binary',
    'other'
);


ALTER TYPE public.gender_type OWNER TO postgres;

--
-- TOC entry 883 (class 1247 OID 32872)
-- Name: notification_status_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.notification_status_type AS ENUM (
    'read',
    'unread'
);


ALTER TYPE public.notification_status_type OWNER TO postgres;

--
-- TOC entry 874 (class 1247 OID 32846)
-- Name: status_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.status_type AS ENUM (
    'active',
    'ended'
);


ALTER TYPE public.status_type OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 235 (class 1259 OID 32910)
-- Name: exercise_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise_categories (
    id bigint NOT NULL,
    name text NOT NULL COLLATE pg_catalog.pg_c_utf8
);


ALTER TABLE public.exercise_categories OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 32998)
-- Name: exercise_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercise_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 32852)
-- Name: goals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.goals (
    id bigint NOT NULL,
    status public.status_type,
    start_date date NOT NULL,
    end_date date NOT NULL,
    user_id bigint,
    target double precision NOT NULL,
    title text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.goals OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 32851)
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.goals ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 32878)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    message text NOT NULL COLLATE pg_catalog.pg_c_utf8,
    status public.notification_status_type NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 32877)
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 32858)
-- Name: progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.progress (
    id bigint NOT NULL,
    current_value bigint NOT NULL,
    updated_at date NOT NULL,
    goal_id bigint NOT NULL
);


ALTER TABLE public.progress OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 32857)
-- Name: progress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.progress ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 32894)
-- Name: session_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session_exercises (
    id bigint NOT NULL,
    sets bigint,
    reps bigint,
    weight_used bigint,
    duration double precision,
    calories_burned bigint,
    notes text COLLATE pg_catalog.pg_c_utf8,
    session_id bigint NOT NULL,
    type_exercise_id bigint NOT NULL,
    name text
);


ALTER TABLE public.session_exercises OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 32893)
-- Name: session_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.session_exercises ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.session_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 32886)
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    date date NOT NULL,
    duration double precision NOT NULL,
    notes text COLLATE pg_catalog.pg_c_utf8,
    user_id bigint NOT NULL,
    title text
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 32885)
-- Name: session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 32902)
-- Name: type_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_exercises (
    id bigint NOT NULL,
    name text NOT NULL COLLATE pg_catalog.pg_c_utf8,
    description text NOT NULL COLLATE pg_catalog.pg_c_utf8,
    calories_burned_per_min bigint NOT NULL,
    exercise_category_id bigint NOT NULL
);


ALTER TABLE public.type_exercises OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 32901)
-- Name: type_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type_exercises ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.type_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 32864)
-- Name: types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.types (
    id bigint NOT NULL,
    title text NOT NULL COLLATE pg_catalog.pg_c_utf8
);


ALTER TABLE public.types OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 32863)
-- Name: type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.types ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 32835)
-- Name: user_stats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_stats (
    id bigint NOT NULL,
    created_at date NOT NULL,
    height double precision NOT NULL,
    weight double precision NOT NULL,
    bmi double precision,
    body_fat_percentage double precision,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_stats OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 32834)
-- Name: user_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_stats ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 32801)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    first_name text NOT NULL COLLATE pg_catalog.pg_c_utf8,
    email text NOT NULL COLLATE pg_catalog.pg_c_utf8,
    password text NOT NULL COLLATE pg_catalog.pg_c_utf8,
    birth_date date NOT NULL,
    avatar text COLLATE pg_catalog.pg_c_utf8,
    gender public.gender_type NOT NULL,
    last_name text DEFAULT ''::text
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 32800)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4995 (class 0 OID 32910)
-- Dependencies: 235
-- Data for Name: exercise_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercise_categories (id, name) FROM stdin;
1	Running
2	Swimming
3	Stretching
4	Cycling
5	Yoga
8	Arms
9	Legs
10	Abs
11	Chest
12	Back
13	Shoulders
14	Calves
15	Cardio
\.


--
-- TOC entry 4982 (class 0 OID 32852)
-- Dependencies: 222
-- Data for Name: goals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.goals (id, status, start_date, end_date, user_id, target, title) FROM stdin;
1	active	2025-05-23	2025-09-01	1	70	Perdre du poids
2	active	2025-05-24	2025-07-12	1	250	Courrir
\.


--
-- TOC entry 4988 (class 0 OID 32878)
-- Dependencies: 228
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, message, status, user_id) FROM stdin;
38	Bonjour ! N'oubliez pas d’ajouter vos progrès aujourd’hui 💪	unread	1
39	Bonjour ! N'oubliez pas d’ajouter vos progrès aujourd’hui 💪	unread	1
40	Vous n'avez pas mis à jour vos progrès pour l’objectif "Perdre du poids". Où en êtes-vous ? 🤔	unread	1
41	Vous n'avez pas mis à jour vos progrès pour l’objectif "Courrir". Où en êtes-vous ? 🤔	unread	1
42	Bonjour ! N'oubliez pas d’ajouter vos progrès aujourd’hui 💪	unread	1
44	Vous n'avez pas mis à jour vos progrès pour l’objectif "Courrir". Où en êtes-vous ? 🤔	read	1
43	Vous n'avez pas mis à jour vos progrès pour l’objectif "Perdre du poids". Où en êtes-vous ? 🤔	read	1
\.


--
-- TOC entry 4984 (class 0 OID 32858)
-- Dependencies: 224
-- Data for Name: progress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.progress (id, current_value, updated_at, goal_id) FROM stdin;
1	80	2025-05-23	1
2	5	2025-05-23	2
3	79	2025-05-23	1
4	78	2025-05-23	1
5	79	2025-05-23	1
6	10	2025-05-23	2
7	25	2025-05-23	2
8	78	2025-05-23	1
9	30	2025-05-23	2
\.


--
-- TOC entry 4992 (class 0 OID 32894)
-- Dependencies: 232
-- Data for Name: session_exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.session_exercises (id, sets, reps, weight_used, duration, calories_burned, notes, session_id, type_exercise_id, name) FROM stdin;
\.


--
-- TOC entry 4990 (class 0 OID 32886)
-- Dependencies: 230
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, date, duration, notes, user_id, title) FROM stdin;
1	2025-05-25	60	Jogging dans foret	1	Jogging
2	2025-05-25	40	Courtes pauses chaque 200 metres	1	Natation
3	2025-05-25	20	Courtes pauses chaque 5 minutes	1	Abdo
4	2025-05-25	20	Courtes pauses	1	Abdos
5	2025-05-25	20	Courtes pauses	1	Abdos
6	2025-05-25	20	bb	1	bb
7	2025-05-25	20	bb	1	bb
8	2025-05-25	20	bb	1	bb
9	2025-05-25	20	bb	1	bb
10	2025-05-25	20	test	1	test
\.


--
-- TOC entry 4994 (class 0 OID 32902)
-- Dependencies: 234
-- Data for Name: type_exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_exercises (id, name, description, calories_burned_per_min, exercise_category_id) FROM stdin;
1	Marches	<ol><li>Tenez-vous debout face à une chaise</li><li>Montez sur la chaise</li><li>Descendez de la chaise</li><li>Répétez</li></ol>	5	9
2	Genoux hauts	<ol><li>Courez sur place, en plaçant les genoux aussi haut que possible et en changeant de jambe à un rythme rapide</li></ol>	5	15
3	Fentes	<ol><li>Tenez-vous debout, le dos droit</li><li>Faites un grand pas en avant avec votre jambe gauche</li><li>Descendez votre bassin jusqu'à ce que votre genou droit touche presque le sol.</li><li>Remontez votre bassin</li><li>Revenez à la position debout en faisant un pas en arrière</li><li>Répétez l'opération en changeant de jambe à chaque fois</li></ol>	5	9
4	Pompes avec rotation	<ol><li>Faites une pompe standard :</li></ol><p>1.a Allongez-vous sur le ventre1.b Placez vos mains près de vos oreilles1.c Utilisez vos bras pour soulever votre ventre jusqu'à ce que les bras soient droits, en gardant le dos droit1.d Pliez les bras jusqu'à ce que la poitrine touche presque le sol, en vous assurant que le dos est droit1.e Soulevez à nouveau votre ventre et revenez à l'étape 1.c</p><ol start="2"><li>Faites pivoter votre corps sur le côté pour que le dos soit droit, que la main inférieure soutenant le corps soit complètement étendue et que seuls la main et le pied inférieurs touchent le sol</li><li>Répétez, en changeant de côté à chaque fois</li></ol>	5	8
5	Fentes latérales gauches	<ol><li>Tenez-vous droit et faites une large foulée latérale, juste supérieure à la largeur des épaules</li><li>Pliez un genou jusqu'à ce que votre cuisse soit parallèle au sol. Le genou plié doit être aligné avec le pied</li><li>Revenez à la position de départ et répétez.</li></ol>	5	9
6	Fentes latérales droites	<ol><li>Tenez-vous droit et faites une large foulée latérale, juste supérieure à la largeur des épaules</li><li>Pliez un genou jusqu'à ce que votre cuisse soit parallèle au sol. Le genou plié doit être aligné avec le pied</li><li>Revenez à la position de départ et répétez.</li></ol>	5	9
7	Squats bulgares gauches	<ol><li>Tenez-vous droit devant une chaise et faites un grand pas. Placez la partie supérieure de l'un de vos pieds sur la chaise</li><li>Pliez le genou avant, en équilibre avec les bras jusqu'à ce que le genou arrière touche presque le sol</li><li>Revenez à la position de départ et répétez.</li></ol>	5	9
8	Squats bulgares droites	<ol><li>Tenez-vous droit devant une chaise et faites un grand pas. Placez la partie supérieure de l'un de vos pieds sur la chaise</li><li>Pliez le genou avant, en équilibre avec les bras jusqu'à ce que le genou arrière touche presque le sol</li><li>Revenez à la position de départ et répétez.</li></ol>	5	9
9	Extensions de la hanche	<ol><li>Mettez-vous à quatre pattes</li><li>Poussez un pied en arrière jusqu'à ce qu'il soit complètement étendu, en vous concentrant sur les muscles fessiers</li><li>Restez une seconde, puis revenez à la position initiale</li><li>Répétez, en alternant les pieds</li></ol>	5	9
10	Fentes avant gauches	<ol><li>Tenez-vous debout avec le dos droit</li><li>Faites un grand pas en avant avec votre jambe gauche</li><li>Abaissez votre bassin jusqu'à ce que vous touchiez presque le sol avec votre genou droit</li><li>Ramenez votre bassin vers le haut</li><li>Répétez à partir de l'étape 3.</li></ol>	5	9
11	Fentes avant droites	<ol><li>Tenez-vous debout avec le dos droit</li><li>Faites un grand pas en avant avec votre jambe gauche</li><li>Abaissez votre bassin jusqu'à ce que vous touchiez presque le sol avec votre genou droit</li><li>Ramenez votre bassin vers le haut</li><li>Répétez à partir de l'étape 3.</li></ol>	5	9
12	Corde à sauter : sauts de base	<p>Cet exercice nécessite une corde à sauter. Assurez-vous que la longueur de la corde est adaptée à votre taille. Une mamière de vérifier est de saisir les deux poignées d'une main et de se tenir au milieu de la corde suspendue au sol avec un pied. Si la corde (sans les poignées) arrive juste sous votre poitrine, sa longueur est correcte. Une corde plus courte serait dangereuse, car vous risqueriez de vous cogner, et une corde plus longue serait mauvaise pour la forme.</p><ol><li>Rapprochez vos pieds, pliez un peu les genoux, gardez la tête et le corps droits, gardez les coudes rentrés, ouvrez les bras.</li><li>Faites tourner uniquement vos poignets avec suffisamment de force pour faire tourner la corde.</li><li>Sautez juste assez haut pour faire passer la corde sous vos pieds.</li><li>Répétez à partir de l'étape 2.</li></ol>	5	15
13	Cercles avant des bras	<ol><li>Tenez-vous debout, le dos bien droit.</li><li>Gardez vos bras droits, amenez les devant vous, puis vers le bas, puis derrière votre dos, puis au dessus de votre tête, puis ramenez les en position initiale, devant vous.</li><li>Continuez à faire des cercles avec vos bras comme décrit à l'étape 2.</li></ol>	5	8
14	Cercle arrière des bras	<ol><li>Tenez-vous debout, le dos droit.</li><li>Gardez vos bras tendus, amenez-les devant vous, levez-les au-dessus de votre tête, puis continuez le mouvement derrière votre dos jusqu'à revenir en position initiale.</li><li>Continuez à faire des cercles comme décrit à l'étape 2.</li></ol>	5	8
15	Escaladeurs de montagne	<p>Position de départ :</p><p>Commencez par la position debout des pompes ou de la planche haute.Les mains doivent se trouver directement sous vos épaules.Gardez la tête dans le prolongement du dos, face au sol.Les pieds doivent être écartés d'environ la largeur des hanches.</p><p>Étapes :</p><ol><li>Déplacez un genou vers le centre de votre corps, vers vos coudes, en gardant l'autre jambe tendue.</li><li>Dans un mouvement de saut rapide, redressez la jambe pliée et tirez l'autre genou vers votre corps.</li><li>Répétez l'étape 2 en alternant les jambes.</li></ol><p>Remarques :</p><p>Tout au long de l'exercice, votre dos doit rester aussi droit que possible – évitez d'avoir une bosse ou un dos affaissé.</p>	5	11
16	Burpees (4 phases)	<p>Position de départ :</p><p>Tenez-vous droit, les pieds écartés de la largeur des hanches.</p><p>Étapes :</p><ol><li>Accroupissez-vous et prenez appui sur le sol avec les mains entre les genoux et devant les pieds, le dos droit.</li><li>En gardant les mains sur le sol, sautez vos jambes vers l'arrière en position de planche haute.</li><li>Sautez vers l'avant pour revenir à la position de squat.</li><li>Répétez l'exercice.</li></ol>	5	11
17	Burpees sans saut	<p>Position de départ :</p><p>Se tenir droit, les pieds écartés de la largeur des hanches.</p><p>Étapes:</p><ol><li>Accroupissez-vous et appuyez-vous sur le sol avec vos mains entre les genoux et devant vos pieds, le dos droit.</li><li>En gardant les mains au sol, donnez une impulsion pour envoyer vos jambes vers l'arrière en position de planche haute.</li><li>Donnez une nouvelle impulsion pour revenir à la position accroupie.</li><li>Sautez.</li><li>Répétez.</li></ol>	5	11
18	Planche haute	Pas de description	5	11
19	Position de l'enfant	Pas de description	5	12
20	Haltères de kettlebell	Pas de description	5	12
21	Développé couché avec haltères	Le mouvement est très similaire au développé couché avec une barre, mais le poids est ramené plus bas sur la poitrine.\nTenez deux haltères et allongez-vous sur un banc. Tenez les haltères près de la poitrine et poussez-les vers le haut jusqu'à ce que les bras soient tendus. Laissez retomber les haltères lentement et de manière contrôlée.	5	11
22	Rotation de l'épaule vers l'avant	Pas de description	5	12
23	Rotation de l'épaule vers l'arrière	Pas de description	5	12
24	Tour de tête	<p>Position de départ :</p><p>Asseyez-vous ou tenez-vous debout, le dos droit et les épaules basses.</p><p>Étapes :</p><ol><li>Asseyez-vous ou tenez-vous debout, le dos droit. Épaules baissées.</li><li>Tournez la tête vers la gauche aussi loin que possible. Arrêtez-vous lorsque vous rencontrez un obstacle et maintenez cette position pendant 5 secondes.</li><li>Revenez à la position centrale.</li><li>Répétez en changeant de côté.</li></ol>	5	13
25	Étirement du cou à gauche	Pas de description	5	13
26	Étirement du cou à droite	Pas de description	5	13
27	Flexion du cou	Pas de description	5	12
28	Planche latérale droite	<ol><li>Allongez-vous sur le côté, le coude inférieur à angle droit, le bras dépassant</li><li>Soulevez votre bassin du sol en soulevant votre épaule inférieure, en gardant l'avant-bras sur le sol ; votre tête, votre bassin et vos pieds doivent être en ligne droite</li><li>Maintenez cette position</li></ol>	5	10
29	Pistol squats droites	<ol><li>Tenez-vous debout sur une jambe, l'autre jambe droite et légèrement en avant</li><li>Pliez lentement un genou, descendez en position accroupie et gardez votre dos et votre autre jambe droits</li><li>Soulevez-vous lentement du squat, en redressant le genou plié et en gardant l'autre jambe droite</li><li>Répéter</li></ol>	5	9
30	Lever du mollet droit	<ol><li>Tenez-vous debout sur le sol ou sur le bord d'une marche pour augmenter l'amplitude des mouvements. Levez un pied en plaçant la partie supérieure sur votre mollet</li><li>Soulevez vos talons jusqu'à ce que vous soyez debout sur les orteils</li><li>Restez dans cette position pendant trois secondes, puis abaissez votre pied sans toucher le sol avec votre talon.</li></ol>	5	14
\.


--
-- TOC entry 4986 (class 0 OID 32864)
-- Dependencies: 226
-- Data for Name: types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.types (id, title) FROM stdin;
1	Perde du poids
\.


--
-- TOC entry 4980 (class 0 OID 32835)
-- Dependencies: 220
-- Data for Name: user_stats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_stats (id, created_at, height, weight, bmi, body_fat_percentage, user_id) FROM stdin;
1	2025-05-22	170	70	24.22	8	1
\.


--
-- TOC entry 4978 (class 0 OID 32801)
-- Dependencies: 218
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, first_name, email, password, birth_date, avatar, gender, last_name) FROM stdin;
1	Clint	clint@est.wood	$2b$12$qfhd2hsrVjMHmacxY9HLnewe37zRlfIg6GpWTvYLHw1JuTqOQXMl2	2000-12-22	1747851878546.png	male	Estwood
\.


--
-- TOC entry 5002 (class 0 OID 0)
-- Dependencies: 236
-- Name: exercise_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercise_categories_id_seq', 15, true);


--
-- TOC entry 5003 (class 0 OID 0)
-- Dependencies: 221
-- Name: goals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.goals_id_seq', 2, true);


--
-- TOC entry 5004 (class 0 OID 0)
-- Dependencies: 227
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 44, true);


--
-- TOC entry 5005 (class 0 OID 0)
-- Dependencies: 223
-- Name: progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.progress_id_seq', 9, true);


--
-- TOC entry 5006 (class 0 OID 0)
-- Dependencies: 231
-- Name: session_exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.session_exercises_id_seq', 1, false);


--
-- TOC entry 5007 (class 0 OID 0)
-- Dependencies: 229
-- Name: session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.session_id_seq', 10, true);


--
-- TOC entry 5008 (class 0 OID 0)
-- Dependencies: 233
-- Name: type_exercise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_exercise_id_seq', 30, true);


--
-- TOC entry 5009 (class 0 OID 0)
-- Dependencies: 225
-- Name: type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_id_seq', 1, true);


--
-- TOC entry 5010 (class 0 OID 0)
-- Dependencies: 219
-- Name: user_stats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_stats_id_seq', 1, true);


--
-- TOC entry 5011 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- TOC entry 4823 (class 2606 OID 32916)
-- Name: exercise_categories exercise_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_categories
    ADD CONSTRAINT exercise_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 32856)
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- TOC entry 4812 (class 2606 OID 32884)
-- Name: notifications notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- TOC entry 4807 (class 2606 OID 32862)
-- Name: progress progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.progress
    ADD CONSTRAINT progress_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 32900)
-- Name: session_exercises session_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_exercises
    ADD CONSTRAINT session_exercises_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 32892)
-- Name: sessions session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- TOC entry 4821 (class 2606 OID 32908)
-- Name: type_exercises type_exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_exercises
    ADD CONSTRAINT type_exercise_pkey PRIMARY KEY (id);


--
-- TOC entry 4809 (class 2606 OID 32870)
-- Name: types type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.types
    ADD CONSTRAINT type_pkey PRIMARY KEY (id);


--
-- TOC entry 4802 (class 2606 OID 32839)
-- Name: user_stats user_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_stats
    ADD CONSTRAINT user_stats_pkey PRIMARY KEY (id);


--
-- TOC entry 4799 (class 2606 OID 32805)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4819 (class 1259 OID 32928)
-- Name: fki_exercise_category_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_exercise_category_id_fk ON public.type_exercises USING btree (exercise_category_id);


--
-- TOC entry 4810 (class 1259 OID 32957)
-- Name: fki_notification_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_notification_id_fk ON public.notifications USING btree (user_id);


--
-- TOC entry 4805 (class 1259 OID 32951)
-- Name: fki_progress_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_progress_id_fk ON public.progress USING btree (goal_id);


--
-- TOC entry 4815 (class 1259 OID 32934)
-- Name: fki_session_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_session_id_fk ON public.session_exercises USING btree (session_id);


--
-- TOC entry 4816 (class 1259 OID 32945)
-- Name: fki_type_exercise_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_type_exercise_id_fk ON public.session_exercises USING btree (type_exercise_id);


--
-- TOC entry 4800 (class 1259 OID 32922)
-- Name: fki_user_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_user_id_fk ON public.user_stats USING btree (user_id);


--
-- TOC entry 4831 (class 2606 OID 32923)
-- Name: type_exercises exercise_category_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_exercises
    ADD CONSTRAINT exercise_category_id_fk FOREIGN KEY (exercise_category_id) REFERENCES public.exercise_categories(id) NOT VALID;


--
-- TOC entry 4827 (class 2606 OID 32952)
-- Name: notifications notification_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notification_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 4826 (class 2606 OID 32946)
-- Name: progress progress_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.progress
    ADD CONSTRAINT progress_id_fk FOREIGN KEY (goal_id) REFERENCES public.goals(id) NOT VALID;


--
-- TOC entry 4829 (class 2606 OID 32929)
-- Name: session_exercises session_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_exercises
    ADD CONSTRAINT session_id_fk FOREIGN KEY (session_id) REFERENCES public.sessions(id) NOT VALID;


--
-- TOC entry 4828 (class 2606 OID 32935)
-- Name: sessions session_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT session_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 4830 (class 2606 OID 32940)
-- Name: session_exercises type_exercise_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_exercises
    ADD CONSTRAINT type_exercise_id_fk FOREIGN KEY (type_exercise_id) REFERENCES public.types(id) NOT VALID;


--
-- TOC entry 4824 (class 2606 OID 32917)
-- Name: user_stats user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_stats
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 4825 (class 2606 OID 32958)
-- Name: goals user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2025-05-26 01:05:38

--
-- PostgreSQL database dump complete
--

